### ISSUE TITLE
A question of sinc filter

### ISSUE THREAD

**Issue by yulei1234** [xinntao/Real-ESRGAN#12]
Hello author, I have a question. SR is a process of denoising and deblurring so that we can add blur and noise to HR image. But the ringing and overshoot artifacts usually appear on the SR result image（HR, not LR）, the method of adding sinc filter on LR is really effective??

**Comment by xinntao** [comment]
@yulei1234 

We want to learn a mapping: LR (with ringing and overshoot artifacts) ----> SR (want to be perfect w/o ringing artifacts). So, we want to simulate LR containing ringing artifacts.   For the synthesis, you can first apply since filter followed by downsampling, or you can downsampling followed by since filter. Both are reasonable. For example, images from cell phones usually have ringing artifacts. If we want to upsample those images, the ringing artifacts are in the LR images.
