### ISSUE TITLE
Error "slow_conv2d_cpu" not implemented for 'Half' If you encounter CUDA out of memory, try to set --tile with a smaller number.

### ISSUE THREAD

**Issue by egorpezdir** [xinntao/Real-ESRGAN#319]
After running 
`python inference_realesrgan.py -n RealESRGAN_x4plus.pth -i inputs` 
i encountered this error:
 `Error "slow_conv2d_cpu" not implemented for 'Half'
If you encounter CUDA out of memory, try to set --tile with a smaller number.`

**Comment by egorpezdir** [comment]
> Please see **Q: Error "slow_conv2d_cpu" not implemented for 'Half'** in https://github.com/xinntao/Real-ESRGAN/blob/master/docs/FAQ.md

but i don't want to run it on CPU. what should i do

**Comment by yangh1368** [comment]
A: In order to save GPU memory consumption and speed up inference, Real-ESRGAN uses half precision (fp16) during inference by default. However, some operators for half inference are not implemented in CPU mode. You need to add --fp32 option for the commands. For example, python inference_realesrgan.py -n RealESRGAN_x4plus.pth -i inputs --fp32.
