### ISSUE TITLE
The usage of _dequeue_and_enqueue function in RealESRNetModel

### ISSUE THREAD

**Issue by YangGangZhiQi** [xinntao/Real-ESRGAN#44]
Hi,
    I read the code serveral times, but cannot figure out what the role of _dequeue_and_enqueue function in RealESRNetModel is. This function is only used in feed_data(),   which just put self.lq and self.gt into self.queue_lq and self.queue_gt. But I cannot find some other codes to use self.queue_lq and self.queue_gt. I would appreciate it if someone could explain this.

**Comment by xinntao** [comment]
https://github.com/xinntao/Real-ESRGAN/blob/b28958cdf2067ee7ed8217387589129eaafb5a0b/realesrgan/models/realesrgan_model.py#L162

This line will call _dequeue_and_enqueue

**Comment by YangGangZhiQi** [comment]
@xinntao Yes, this line call self._dequeue_and_enqueue(). I just cannot figure out how your code use self.queue_lq and self.queue_gt  . I cannot find some other codes to use this two member variables。I know the role of this code block is to put input data in training pool. How does the code reach this goal？

**Comment by xinntao** [comment]
![image](https://user-images.githubusercontent.com/17445847/130611454-baca5e7c-232f-477e-a03f-0e4762b829f1.png)

1. It first randomly shuffle the image in the pool
2. then get first N samples for self.lq and self.gt
3. Finally, we obtain the shuffled self.lq and self.gt

**Comment by YangGangZhiQi** [comment]
I get it. Thanks for so your patient explain!  So poor my understanding about the _dequeue_and_enqueue function!

**Comment by Arseny-N** [comment]
Hi, @xinntao. Thank you for the awesome work !

I also somewhat do not understand the purpose of this function. 
Why do we need to sample the training batch from a pool of images ? 

As far as I can tell the most obvious reason is to avoid creating batch
from sequential indices.  But we already shuffle the indices in EnlargedSampler.   
So the will not be sequential.

On the other hand the shuffling may result in some samples being used more
then once. Is this done because the latter is  a technique for improving  training ? 


Thanks in advance, 
Arseny

**Comment by xinntao** [comment]
@Arseny-N 
Batch processing in pytorch limits the diversity of synthetic degradations in a batch. For example, samples in a batch could not have different resize scaling factors. Therefore, we employ a training pair pool to increase the degradation diversity in a batch.

**Comment by Arseny-N** [comment]
Thank you for the timely explanation!
