### ISSUE TITLE
realesrgan-x4plus model mixes image parts order when use -s

### ISSUE THREAD

**Issue by merdekiti** [xinntao/Real-ESRGAN#554]
It happens with portable version on windows and linux.
Example of commands I run:
./realesrgan-ncnn-vulkan.exe -i alita.jpg -o output.jpg -n realesrgan-x4plus -s 2 ( doesn't work well)
./realesrgan-ncnn-vulkan.exe -i alita.jpg -o output.jpg -n realesrgan-x4plus (works well)

**Comment by TechnoMasterBoy** [comment]
When will people learn to read... It is called x4 for a reason.
If you want to use an x4 model as an x2 model, you'll have to edit it. It is quite simple to do.

**Comment by merdekiti** [comment]
I read the instructions quite carefully. The thing is that - it confuses me (and other people as well) a bit. We have this parameter
`-s scale             upscale ratio (can be 2, 3, 4. default=4)`
And it doesn't warn you if you run the wrong model.

>If you want to use an x4 model as an x2 model, you'll have to edit it. It is quite simple to do.
Is there an instruction on how to edit it? I found X2 model here https://github.com/xinntao/Real-ESRGAN/blob/master/docs/model_zoo.md but it's in .pth format and should be converted into ncnn (which is quite tricky to do).

**Comment by TechnoMasterBoy** [comment]
> I read the instructions quite carefully. The thing is that - it confuses me (and other people as well) a bit. We have this parameter `-s scale upscale ratio (can be 2, 3, 4. default=4)` And it doesn't warn you if you run the wrong model.

That parameter is meant for the animevideo model.

> Is there an instruction on how to edit it?

You'll have to make a copy of the realesrgan-x4plus.bin and realesrgan-x4plus.param, name them something like realesrgan-x2plus
then edit the .param file. Open it in notepad++, at the bottom there's a "Resize_1181"
Which has these values: 1 1 1885 1890 0=1 1=2.000000e+00 2=2.000000e+00
Both of the "2.000000e+00" need to be replaced with 1.000000e+00
Then when you use it, you simply just do like this:
./realesrgan-ncnn-vulkan.exe -i alita.jpg -o output.jpg -n realesrgan-x2plus -s 2
Keep in mind that it'll still take just as long to upscale as it would 4x and uses just as much VRAM.
But it atleast saves you the trouble of downscaling afterwards.

If you want it already done, I can just send you the models.
https://files.catbox.moe/kzabwo.7z
Just put the 2 files into your "models" folder"

By the way, you can easily make a .bat file that will upscale all of your images instead of you doing 1 by 1 manually.
If you want that, let me know.

**Comment by merdekiti** [comment]
@TechnoMasterBoy I have just tested the changes in realesrgan-x4plus.param that you recommended. Everything works perfectly! Really thank you a lot for your help! Maybe it is worth adding this short instruction to the documentation. It will cover a lot of questions.

I have a question regarding [RealESRGAN_x2plus](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth) Does this model work the same way as X4 (in context of time and resources)? Is it a completely different model that is optimized for X2  (works much faster than X4)?

>By the way, you can easily make a .bat file that will upscale all of your images instead of you doing 1 by 1 manually.

In the documentation, I found information that I can do bulk upscale. To do that I need to feed a folder path instead of a single file. I have also tested it and it works just perfectly :) Thanks again.

**Comment by TechnoMasterBoy** [comment]
> I have a question regarding [RealESRGAN_x2plus](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth) Does this model work the same way as X4 (in context of time and resources)? Is it a completely different model that is optimized for X2 (works much faster than X4)?

I am not sure about the python model of the x2plus as I haven't tested it. Generally I stay away from python as it's significantly slower.

**Comment by merdekiti** [comment]
Got it. I'm closing this issue because you helped to solve it. Thanks a lot for your help!

**Comment by PeteJobi** [comment]
Hello, @TechnoMasterBoy. I've tried your x2 model. The result is as expected. But you mentioned that it takes the same amount of time and resources as x4. Can anything be done about this? If not, how can I obtain a true x2 model?
