### ISSUE TITLE
replicate demo suddenly not working

### ISSUE THREAD

**Issue by pakieFNF** [xinntao/Real-ESRGAN#656]
it seems that the replicate demo has suddenly borked itself, with no real explanation, the error you get when you try to upscale is below: 
Prediction input failed validation: {"detail":[{"loc":["body","input","tile"],"msg":"none is not an allowed value","type":"type_error.none.not_allowed"}]}
this happens even if you are logged in with your github account or if you use the demo image, so i have no idea why it would even fail in the first place

**Comment by TerryBrand231** [comment]
Hey @pakieFNF , sorry that you're having trouble with using Replicate. I believe the solution can be seen within the error message, stating that **"none is not an allowed value" with the input field, being `tile`**. This is suggesting that you must enter a value in the tile field. From what I've read, a value of 0 suggest no tile, so you can input that. You can also try 400 or a higher value when receiving an Out of Memory error which commonly occurs with larger images. Perhaps Replicate changed something, since the last push to [xinntao/realesrgan](https://replicate.com/xinntao/realesrgan) was 10 months ago, and this issue seems relatively new. I have confirmed it works when you enter `0` as the `tile` value 😊
