### ISSUE TITLE
Wired output

### ISSUE THREAD

**Issue by iBobbyTS** [xinntao/Real-ESRGAN#72]
Here's the configuration
```!python inference_realesrgan.py --model_path experiments/pretrained_models/RealESRGAN_x4plus.pth --input upload --netscale 4 --outscale 3.5 --half --ext png --face_enhance```
Original
![MVC-006F](https://user-images.githubusercontent.com/46138297/132710095-f7c79fd4-5253-4e6e-8215-106b015b483d.JPG)

Upsampled
![MVC-006F_out](https://user-images.githubusercontent.com/46138297/132710201-276c41b6-3ac9-429c-94b3-4baaaa930afe.jpg)

Wired stamp on the eye
<img width="618" alt="Screen Shot 2021-09-09 at 10 56 47 PM" src="https://user-images.githubusercontent.com/46138297/132710285-310b286d-1875-4a4f-b6b2-c43edcf9cfdd.png">

**Comment by xinntao** [comment]
@iBobbyTS 
Thanks for your feedback 👍 
This is because of the wrong prediction of the face detector, that is, it detects a `face' in the eye. 

You can have a quick fix by turning off the face_enhance function. 

I will also try to improve it~

**Comment by xinntao** [comment]
Here is more detailed information, after I look inside into this issue:


Now it does not support well for side faces:

This is the output result：
![image](https://user-images.githubusercontent.com/17445847/132791666-940b4016-971f-4de5-9284-4f7f7a7461c1.png)

However, GFPGAN requires alignments to this template:
![image](https://user-images.githubusercontent.com/17445847/132791771-c736caa6-5210-475a-a974-9d83a058517c.png)

So, an error arises here. After alignment, it produces wrong alignment output:

![image](https://user-images.githubusercontent.com/17445847/132791870-3f0443f0-6b6c-4fa8-a515-c1f3c1e94c3a.png)

After pasting back to the original image, it produces weird output.

**Comment by xinntao** [comment]
A fix in facexlib package, which used by face restoration:
remove faces with too small eye distance, such as side faces or too small faces

https://github.com/xinntao/facexlib/commit/1a8f08ca175fd24e67ca4b91ea5d82e0543d5266

Will release in the next facexlib release. 

Thanks for reporting this bug. 😄

**Comment by xinntao** [comment]
If there is no further question, I will close this issue. 
please open it when you need more discussion. Thanks~

**Comment by LiangbinXie** [comment]
Thanks for reporting this problem! This is due to the false detection of the face and we have fixed this bug! Please try our algorithm again and let me know if you encounter the problem again~

2021-09-09 22:58:11"iBobby" ***@***.***>写道：

Here's the configuration
!python inference_realesrgan.py --model_path experiments/pretrained_models/RealESRGAN_x4plus.pth --input upload --netscale 4 --outscale 3.5 --half --ext png --face_enhance
Original


Upsampled


Wired stamp on the eye


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xinntao** [comment]
@iBobbyTS 
You can now update facexlib to 0.2.1.0 for fix this bug: https://pypi.org/project/facexlib/0.2.1.0/
